const state={id:"",name:"",ws:null,peers:[],pc:null,chatEl:null,peersEl:null,localVideo:null,remoteVideo:null,lowBw:false,audioOnly:false,remoteDescSet:false,pendingCandidates:[],target:null,incomingFrom:null,pendingOffer:null,incomingAccepted:false}
function init(){const saved=localStorage.getItem("rtc_id");state.id=saved||Math.random().toString(36).slice(2);if(!saved)localStorage.setItem("rtc_id",state.id);state.chatEl=document.getElementById("chat");state.peersEl=document.getElementById("peers");state.localVideo=document.getElementById("localVideo");state.remoteVideo=document.getElementById("remoteVideo");document.getElementById("join").onclick=join;document.getElementById("send").onclick=sendMsg;document.getElementById("call").onclick=startCall;document.getElementById("hangup").onclick=hangup;document.getElementById("lowBw").onchange=(e)=>{state.lowBw=e.target.checked};document.getElementById("audioOnly").onchange=(e)=>{state.audioOnly=e.target.checked};document.getElementById("name").addEventListener("change",join);document.getElementById("accept").onclick=acceptCall;document.getElementById("reject").onclick=rejectCall;connectWS();fetchDiag()}
function connectWS(){const proto="wss";state.ws=new WebSocket(`${proto}://${location.host}/ws`);state.ws.onopen=()=>{join()};state.ws.onmessage=(ev)=>{const m=JSON.parse(ev.data);if(m.type==="peers"){state.peers=m.peers;renderPeers()}else if(m.type==="chat"){appendChat(`${m.from}:${m.text}`)}else if(m.type==="signal"){handleSignal(m)}};state.ws.onclose=()=>{setTimeout(connectWS,2000)}}
function join(){const n=document.getElementById("name").value||"guest";state.name=n;state.ws&&state.ws.send(JSON.stringify({type:"join",id:state.id,name:n}))}
function renderPeers(){state.peersEl.innerHTML="";state.peers.filter(p=>p.id!==state.id).forEach(p=>{const li=document.createElement("li");li.textContent=`${p.name} (${p.id.slice(0,4)})`;li.onclick=()=>startCall(p.id);state.peersEl.appendChild(li)})}
function appendChat(t){const d=document.createElement("div");d.textContent=t;state.chatEl.appendChild(d);state.chatEl.scrollTop=state.chatEl.scrollHeight}
function sendMsg(){const t=document.getElementById("msg").value;if(!t)return;state.ws.send(JSON.stringify({type:"chat",from:state.id,text:t}))}
async function setupLocalStream(){const v=!state.audioOnly;const vc=state.lowBw?{width:{ideal:320,max:320},height:{ideal:240,max:240},frameRate:{ideal:12,max:15}}:{width:{ideal:640,max:640},height:{ideal:360,max:360},frameRate:{ideal:15,max:20}};const s=await navigator.mediaDevices.getUserMedia({video:v?vc:false,audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.localVideo.srcObject=v?s:null;try{state.ws&&state.ws.send(JSON.stringify({type:"media",from:state.id,audio:s.getAudioTracks().length>0,video:s.getVideoTracks().length>0}))}catch{}return s}
function createPC(){const pc=new RTCPeerConnection({iceServers:[],bundlePolicy:"max-bundle",iceCandidatePoolSize:2});pc.addTransceiver("audio",{direction:"sendrecv"});if(!state.audioOnly)pc.addTransceiver("video",{direction:"sendrecv"});pc.onicecandidate=(e)=>{if(e.candidate){state.ws.send(JSON.stringify({type:"signal",to:state.target,from:state.id,candidate:e.candidate}))}};pc.ontrack=(e)=>{if(!state.remoteVideo.srcObject)state.remoteVideo.srcObject=new MediaStream();state.remoteVideo.srcObject.addTrack(e.track);try{state.remoteVideo.play()}catch{}};pc.onconnectionstatechange=()=>{appendChat(`rtc:${pc.connectionState}`)};return pc}
async function startCall(target){if(state.pc)return;if(target)state.target=target;else{const p=state.peers.find(x=>x.id!==state.id);if(!p)return;state.target=p.id}state.ws.send(JSON.stringify({type:"signal",to:state.target,from:state.id,ring:true,name:state.name}));state.pc=createPC();const s=await setupLocalStream();s.getTracks().forEach(t=>state.pc.addTrack(t,s));state.pc.getSenders().forEach(sd=>{const p=sd.getParameters();if(!p.encodings)p.encodings=[{}];if(sd.track&&sd.track.kind==="video")p.encodings[0].maxBitrate=state.lowBw?200000:350000;else if(sd.track&&sd.track.kind==="audio")p.encodings[0].maxBitrate=32000;sd.setParameters(p).catch(()=>{})});const off=await state.pc.createOffer();await state.pc.setLocalDescription(off);state.ws.send(JSON.stringify({type:"signal",to:state.target,from:state.id,sdp:off}))}
async function handleSignal(m){if(m.ring){state.incomingFrom=m.from;document.getElementById("incomingText").textContent=`${m.name||m.from} is calling...`;document.getElementById("incomingBar").style.display="flex";return}if(m.sdp){state.target=m.from;if(m.sdp.type==="offer"){if(!state.incomingAccepted){state.pendingOffer=m;document.getElementById("incomingText").textContent=`${m.name||m.from||"peer"} is calling...`;document.getElementById("incomingBar").style.display="flex";return}if(!state.pc)state.pc=createPC();await state.pc.setRemoteDescription(new RTCSessionDescription(m.sdp));state.remoteDescSet=true;while(state.pendingCandidates.length){const c=state.pendingCandidates.shift();try{await state.pc.addIceCandidate(c)}catch{}}const s=await setupLocalStream();s.getTracks().forEach(t=>state.pc.addTrack(t,s));state.pc.getSenders().forEach(sd=>{const p=sd.getParameters();if(!p.encodings)p.encodings=[{}];if(sd.track&&sd.track.kind==="video")p.encodings[0].maxBitrate=state.lowBw?200000:350000;else if(sd.track&&sd.track.kind==="audio")p.encodings[0].maxBitrate=32000;sd.setParameters(p).catch(()=>{})});const ans=await state.pc.createAnswer();await state.pc.setLocalDescription(ans);state.ws.send(JSON.stringify({type:"signal",to:m.from,from:state.id,sdp:ans}));document.getElementById("incomingBar").style.display="none";state.pendingOffer=null;state.incomingAccepted=false}else{if(!state.pc)state.pc=createPC();await state.pc.setRemoteDescription(new RTCSessionDescription(m.sdp));state.remoteDescSet=true;while(state.pendingCandidates.length){const c=state.pendingCandidates.shift();try{await state.pc.addIceCandidate(c)}catch{}}}}else if(m.candidate){const c=new RTCIceCandidate(m.candidate);if(state.pc&&state.remoteDescSet){try{await state.pc.addIceCandidate(c)}catch{}}else{state.pendingCandidates.push(c)}}}
function hangup(){if(state.pc){state.pc.getSenders().forEach(s=>{try{s.track.stop()}catch{}});state.pc.close();state.pc=null}}
async function fetchDiag(){try{const r=await fetch("/diag");const j=await r.json();document.getElementById("diag").textContent=JSON.stringify(j,null,2)}catch{}}
document.addEventListener("DOMContentLoaded",init)
function join(){const n=document.getElementById("name").value||"guest";state.name=n;state.ws&&state.ws.send(JSON.stringify({type:"join",id:state.id,name:n}))}
function acceptCall(){state.incomingAccepted=true;try{state.remoteVideo.play()}catch{};if(state.pendingOffer){handleSignal(state.pendingOffer)}}
function rejectCall(){document.getElementById("incomingBar").style.display="none";state.incomingAccepted=false;state.pendingOffer=null;state.ws&&state.ws.send(JSON.stringify({type:"signal",to:state.incomingFrom,from:state.id,reject:true}))}